apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingpongmania-ingress
  namespace: pingpongmania-dev
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: play-service
            port:
              number: 80
