apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: pingpongmania
build:
  artifacts:
  - image: pong-service
    context: src
    docker:
      dockerfile: PongService/Dockerfile
  - image: ping-service
    context: src
    docker:
      dockerfile: PingService/Dockerfile
  - image: play-service
    context: src
    docker:
      dockerfile: PlayService/Dockerfile
deploy:
  kubectl:
    manifests:
    - deploy\namespace.yaml
    # Dapr components
    - deploy\dapr\appconfig.yaml
    - deploy\dapr\servicebus.yaml
    - deploy\dapr\statestore.yaml
    # Kubernetes manifests
    - deploy\manifests\pong-service\deployment.yaml
    - deploy\manifests\ping-service\deployment.yaml
    - deploy\manifests\play-service\deployment.yaml
    - deploy\manifests\ingress.yaml
