apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pingpongmania-pubsub
  namespace: pingpongmania-dev
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      key: connectionString
      name: asb-connection-string
auth:
  secretStore: kubernetes