apiVersion: v1
kind: Service
metadata:
  name: pong-service
  namespace: pingpongmania-dev
  labels:
    app: pong-service
spec:
  type: ClusterIP
  selector:
    app: pong-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-service
  namespace: pingpongmania-dev
  labels:
    app: pong-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-service
  template:
    metadata:
      labels:
        app: pong-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pong-api"
        dapr.io/app-port: "5000"
    spec:
      containers:
      - name: pong-service
        image: pong-service
        ports:
          - containerPort: 5000
            protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 200Mi